name: Docker Build and Push
on:
  push:
    branches:
      - 'main'

jobs:
  find_changed_modules:
    runs-on: 'ubuntu-latest'
    outputs:
      modules: ${{ steps.find_changed_modules.outputs.modules }}
    steps:
    - uses: actions/checkout@v3
    - id: find_changed_modules
      uses: withlazers/find-changed-modules-action@main
      with:
        prefix_dir: docker

  docker_push:
    runs-on: 'ubuntu-latest'
    needs:
    - find_changed_modules
    if: ${{ needs.find_changed_modules.outputs.services != '[]' }}
    strategy:
      matrix:
        module: ${{ fromJSON(needs.find_changed_modules.outputs.modules) }}
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        archs: "386, amd64, arm64, arm"
        image: withlazers/${{ matrix.module }}
        tags: sha-${{ github.sha }} latest ${{ github.ref_name }}
        context: ./docker/${{ matrix.module }}
        containerfiles: Dockerfile
    - name: Push to Dockerhub
      id: push-to-docker
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: docker.io/withlazers
        username: withlazers
        password: ${{ secrets.DOCKER_TOKEN }}
